### ISSUE TITLE
Misused header 'content-type' Async

### ISSUE THREAD

**Issue by Sven286** [stefan-epic/Zabbix-6.0-Api#4]
Hi,

I just started to use this nuget package for connecting to the api of my zabbix 6.0.23 installation.
I created my new project as .Net 8 application and want to use asynchrone methods.
Receiving all host groups gives me the following exception.

`var groups = await _zabbixCore.HostGroups.GetAsync()`

```
System.InvalidOperationException: Misused header name, 'content-type'. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
   at System.Net.Http.Headers.HttpHeaders.GetHeaderDescriptor(String name)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
   at Zabbix.Core.ZabbixCore.SendRequestAsync[T](Object params, String method, String token)
   at Zabbix.Core.ZabbixCore.SendRequestAsync[T](Object params, String method)
   at Zabbix.Services.CrudServices.GetService`2.GetAsync(TEntityFilter filter)
   at Zabbix.Services.CrudServices.CrudService`3.GetAsync(TEntityFilter filter)
```

When I call the method synchroniously everything works fine.
`var groups = _zabbixCore.HostGroups.Get()`

I Suspect the following line of code to be the issue, but I don't know why this piece is added:
https://github.com/stefan-epic/Zabbix-6.0-Api/blob/39d73b09cfcc510e3f311523ba56e4234af7be21/Zabbix/Core/ZabbixCore.cs#L134

**Comment by stefan-epic** [comment]
I will look into this when I get the time thanks for making the issue :)

**Comment by Scriptman** [comment]
Just remove the line 134 in ZabbixCore.cs:
this._httpClient.DefaultRequestHeaders.Add("content-type", "application/json-rpc");

It's in the SendRequestAsync<T>(object? @params, string method, string? token) method.

You don't use this in the non-Async request.

**Comment by stefan-epic** [comment]
Sorry this took so long, I was very busy. Should be fixed now

**Comment by alex-dolzhok** [comment]
Could you please create a new version of NuGet package because there is still a line with issue in ZabbixCore.cs 1.2.5 version?

![Image](https://github.com/user-attachments/assets/26abb251-0b81-4c1e-b00c-f6b7f4c2ebff)

**Comment by stefan-epic** [comment]
> Could you please create a new version of NuGet package because there is still a line with issue in ZabbixCore.cs 1.2.5 version?
> 
> ![Image](https://github.com/user-attachments/assets/26abb251-0b81-4c1e-b00c-f6b7f4c2ebff)

Thank you for pointing this out. Should be fixed now.
